controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:739561048503:certificate/b2d5c2b3-246d-4de2-8055-878c3633ad13
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
